---
# tasks file for delete user

- hosts: all
  tasks:
    - name: Delete account for user
      user:
        name: "{{ username }}"
        remove: yes
        state: absent

    - name: Remove user from /etc/sudoers (if they were in there)
      lineinfile:
        dest: /etc/sudoers
        state: absent
        regexp: '^{{ username }} ALL\='
        validate: 'visudo -cf %s'
