---
# tasks file for delete user

- name: Delete user
  hosts: all
  tasks:
    - name: Delete account for user
      ansible.builtin.user:
        name: "{{ username }}"
        remove: yes
        state: absent
