---
# tasks file for create user

- hosts: all
  vars:
    # Default to false; this can be overridden via:
    #  ansible-playbook --extra-vars="allow_sudo=true"
    allow_sudo: false
  tasks:
    - name: Create account for user
      user:
        name: "{{ username }}"
        shell: /bin/bash

    - name: Set home directory permissions
      file:
        mode: 0750
        path: /home/{{ username }}

    - name: Add ssh public key as authorized key for user
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('aws_ssm', ssm_public_key, region=ssm_region) }}"

    - name: Allow user to use sudo without password
      block:
        - name: Ensure sudo-nopw group exists
          group:
            name: sudo-nopw
            state: present

        - name: Allow sudo-nopw group to use sudo without password
          lineinfile:
            dest: /etc/sudoers
            state: present
            regexp: '^%sudo-nopw ALL\='
            line: '%sudo-nopw ALL=(ALL) NOPASSWD:ALL'
            validate: 'visudo -cf %s'

        - name: Add user to sudo-nopw group
          user:
            name: "{{ username }}"
            groups: sudo-nopw
      when: allow_sudo|bool
