---
# tasks file for create user

- hosts: all
  tasks:
    - name: Create account for user
      user:
        name: "{{ username }}"
        shell: /bin/bash

    - name: Add ssh public key as authorized key for user
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('aws_ssm', '{{ ssm_public_key }}') }}"
