---
# tasks file for create user

- hosts: all
  tasks:
    - name: Create account for user
      user:
        name: "{{ username }}"
        shell: /bin/bash

    - name: Add ssh public key as authorized key for user
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('aws_ssm', '{{ ssm_public_key }}') }}"

    - name: Allow user to use sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^{{ username }} ALL\='
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
      when: allow_sudo|bool
