---
# tasks file for create user

- hosts: all
  vars:
    # Default to false; this can be overridden via:
    #  ansible-playbook --extra-vars="allow_sudo=true"
    allow_sudo: false
  tasks:
    - name: Create account for user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash

    - name: Set home directory permissions
      ansible.builtin.file:
        mode: 0750
        path: /home/{{ username }}

    - name: Add ssh public key as authorized key for user
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_public_key }}"

    - name: Allow user to use sudo without password
      when: allow_sudo | bool
      block:
        - name: Ensure sudo-nopw group exists
          ansible.builtin.group:
            name: sudo-nopw
            state: present

        - name: Allow sudo-nopw group to use sudo without password
          ansible.builtin.lineinfile:
            dest: /etc/sudoers
            state: present
            regexp: '^%sudo-nopw ALL\='
            line: '%sudo-nopw ALL=(ALL) NOPASSWD:ALL'
            validate: 'visudo -cf %s'

        - name: Add user to sudo-nopw group
          ansible.builtin.user:
            name: "{{ username }}"
            groups: sudo-nopw
